name: mc
channels:
  - nvidia
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - conda==23.5.2
  - setuptools
  - pip
  - wheel
  - conda-content-trust
  - conda-libmamba-solver
  - numpy
  - pandas
  - xarray
  - pyproj
  - pathlib
  - pystac-client
  - rasterio
  - stackstac
  - planetary-computer
  - s3fs
  - boto3
  - botocore
  - zarr
  - shapely
  - requests
  - sen2nbar
  - segmentation-models-pytorch
  - odc-stac
  - odc-algo


  - pip:
      - pystac-client
      - planetary-computer
